// Package main provides the entry point for the Stok inventory management API
// This is a multi-tenant backend system for managing inventory, menu items,
// and organizational structures for coffee shops and restaurants.
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"github.com/mnadev/stok/internal/api"
	"github.com/mnadev/stok/internal/database"
	"github.com/mnadev/stok/internal/scheduler"

	"github.com/gin-gonic/gin"
	_ "github.com/mnadev/stok/docs" // This will be generated by swag
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           Stok Inventory Management API
// @version         1.0
// @description     A comprehensive inventory management system for coffee shops and restaurants
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// Get port from environment variable or use default
	// This allows for easy deployment configuration
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	// Initialize Database connection
	// This will connect to PostgreSQL in production or fail if ramsql is requested
	db, err := database.Initialize()
	if err != nil {
		log.Fatalf("Could not initialize database: %v", err)
	}

	// Set up Gin router with default middleware
	// Gin provides logging, recovery, and other useful middleware out of the box
	router := gin.Default()

	// Setup API routes including authentication, organizations, and inventory endpoints
	api.SetupRouter(router, db)

	// Initialize and start the email scheduler
	emailScheduler := scheduler.NewScheduler(db)
	emailScheduler.Start()

	// Swagger documentation route for API exploration
	// Available at /swagger/index.html when server is running
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Health check endpoint for monitoring and load balancers
	// Returns a simple status response to verify the service is running
	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	// Set up graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	// Start the HTTP server in a goroutine
	go func() {
		fmt.Printf("Starting server on port %s\n", port)
		fmt.Printf("Swagger documentation available at: http://localhost:%s/swagger/index.html\n", port)
		if err := router.Run(":" + port); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Failed to run server: %v", err)
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the server
	<-quit
	log.Println("Shutting down server...")

	// Stop the email scheduler
	emailScheduler.Stop()

	log.Println("Server stopped")
}
